name: vita_seniors
description: "VITA is a user-friendly and accessible app designed to help seniors combat loneliness and stay connected with loved ones."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  flutter_tts: ^4.0.2
  googleapis_auth: ^1.6.0
  googleapis: ^13.1.0
  url_launcher: ^6.3.0
  google_generative_ai: ^0.4.3
  speech_to_text: ^6.6.1
  avatar_glow: ^2.0.2
  volume_controller: ^2.0.7
  webview_flutter: ^4.8.0
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.3
  flutter_contacts: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/logo.png
    - assets/memory/memory.json
    - assets/memory/rememberList.json
    - assets/memory/shopList.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
